config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :content, length: {in: 1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def show
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = Blog.create(blog_params)
    if params[:back]
      render :new
    else
      if @blog.save
        redirect_to blogs_path, notice: "Successfully posted！"
      else
        render :new
      end
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "Successfully edited!"
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: "Successfully deleted!"
  end

  def confirm
    @blog = Blog.new(blog_params)
  end

  private
    def set_blog
      @blog = Blog.find(params[:id])
    end

    def blog_params
      params.require(:blog).permit(:name, :title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true, url: choose_new_or_edit) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_name">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="blog_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <%= form.submit %>
<% end %>
<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で送信しますか？</h3>

<%= form_with(model: @blog, local: true) do |form| %>
  <%= form.hidden_field :name %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>

  <p>名前：<%= @blog.name %></p>
  <p>タイトル：<%= @blog.title %></p>
  <p>本文：<%= @blog.content %></p>
  <%= form.submit "登録する" %>
  <%= form.submit '戻る', name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>ブログ一覧</h1>

<table>
    <tr>
      <th>名前</th>
      <th>タイトル</th>
      <th>内容</th>
    </tr>

    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.name %></td>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= link_to '詳細', blog_path(blog.id) %></td>
        <td><%= link_to '編集', edit_blog_path(blog.id) %></td>
        <td><%= link_to '削除', blog_path(blog.id), method: :delete  %></td>
      </tr>
    <% end %>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<h1>ブログ詳細画面</<h1>
<p>名前：<%= @blog.name %></p>
<p>タイトル：<%= @blog.title %></p>
<p>内容：<%= @blog.content %></p>


<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>